# Generated by Django 5.2.16 on 2026-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='address',
            field=models.TextField(default='unknown'),
        ),
    ]
