# Generated by Django 5.2.16 on 2026-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gatecontrol", "0002_accessrequest_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="info",
            field=models.TextField(default=""),
        ),
    ]
